# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd8bdf0258a14ccc753597d1f53f82c2229647f7a127c8e71b69872689b1a922497951175da6ff27e02806b962cf3d03b80a5288e78574d2e2304a842efbd6a9

test:
  secret_key_base: a5f0c3a04ac218d24c9ff7c70adc957a9b49eb87b5ba6e82579b63c4d5b6964bc092b2c4d02787b2a7ff0a7c4b9bbc0e4a5587fa20e897343b97e5f593dee86e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
